wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.0
    start_time: 1675636528.303357
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 1
      - 2
      - 23
      4: 3.10.0
      5: 0.13.9
      6: 4.23.1
      8:
      - 1
      - 5
adap_kl_ctrl:
  desc: null
  value: true
batch_size:
  desc: null
  value: 256
cliprange:
  desc: null
  value: 0.2
cliprange_value:
  desc: null
  value: 0.2
forward_batch_size:
  desc: null
  value: 1
gamma:
  desc: null
  value: 1
horizon:
  desc: null
  value: 10000
init_kl_coef:
  desc: null
  value: 0.2
lam:
  desc: null
  value: 0.95
learning_rate:
  desc: null
  value: 1.41e-05
log_with:
  desc: null
  value: wandb
model_name:
  desc: null
  value: lvwerra/gpt2-imdb
ppo_epochs:
  desc: null
  value: 4
remove_unused_columns:
  desc: null
  value: true
seed:
  desc: null
  value: 0
steps:
  desc: null
  value: 20000
target:
  desc: null
  value: 6
total_ppo_epochs:
  desc: null
  value: 79
tracker_project_name:
  desc: null
  value: trl
vf_coef:
  desc: null
  value: 0.1
